### ISSUE TITLE
Cannot use outputs with DCS bios...

### ISSUE THREAD

**Issue by tao-jcqt** [dcs-bios/dcs-bios#217]
Hello everyone, it's been a while since I wanted to build panels to make flying easier (being the owner of two 3D printers...). So I decided to turn to DCS Bios to link the hardware part to DCS Word. So I did some tests with an Arduino Uno and after a few unsuccessful attempts I manage to make the inputs work: I set a switch for the landing gear (on the Viggen) and it works !!! Nevertheless, I wanted to try later to configure the outputs so that an LED lights up when the landing gear is down. And that's the problem... I have nothing, the LED doesn't light up, even though it's well connected to the Arduino (blinks at startup). I went on the DCS bios online HUB and it seems that the software doesn't retrieve the data from DCS. It displays no "data yet" while the simulator is running and the inputs are working... I can't find the source of the problem. I also just noticed some kind of error message in the DCS bios log (See attached document). 
[DCS-BIOS.log](https://github.com/dcs-bios/dcs-bios/files/4434126/DCS-BIOS.log)

Hope you'll be able to help me...

**Comment by WarLord211** [comment]
i recommend the ED Forum for this kind of questions.
i cant help you because i dont use an arduino. sorry

try here for help: https://forums.eagle.ru/forumdisplay.php?f=101

**Comment by tao-jcqt** [comment]
Okay, thanks. I'll try to take a look over there... But if anyone has the solution, I'm in.

**Comment by tao-jcqt** [comment]
Yet another discovery... I found this message in the DCS log (not bios):
"2020-04-05 17:12:10.330 ERROR Lua::Config: Call error LuaExportAfterNextFrame:<LUA_TTABLE>
stack traceback:
[C]: ?
[C]: in function 'try'.
[string "S:Dcs Bios lua"]:98: in function 'send
162: in function 'flush'...
[string "S:\DCS Bios\dcs-lua\BIOS.lua"]:86: in function < [string "S:\DCS Bios\dcs-lua\BIOS.lua"]:83>."
There's also another error (before this message):
"can't open 'C:\Users\Dawnplayer\Saved Games\DCS\Scripts\DCS-BIOS\BIOS.lua''. I don't really understand the problem... I'm hoping you can help me.

**Comment by tao-jcqt** [comment]
Nobody answers me on the Eagle Dynamics forum, I'm starting to despair... Do you think a new installation of Windows can fix the problem ?

**Comment by derammo** [comment]
Definitely do not reinstall, no.   I can't solve this problem for you but I am currently writing up some notes for you so you can probably fix it.

**Comment by derammo** [comment]
Ok finished reading your stuff.   Here is what the log messages say:

1) "ERROR Lua::Config: Call error LuaExportAfterNextFrame:<LUA_TTABLE>
stack traceback:"

this means DCS was calling out to Export.lua to send the latest information when it crashed and recovered.  There isn't anything specifically interesting in this message.   Like you said, the error happens before there.

2) "can't open 'C:\Users\Dawnplayer\Saved Games\DCS\Scripts\DCS-BIOS\BIOS.lua"

This means Export.lua was trying to initialize the parts of DCS-BIOS that run inside DCS and it either could not find this file or the file has been corrupted.   Either way, this will obviously keep DCS-BIOS from working.

I would proceed like this:

- go to C:\Users\Dawnplayer\Saved Games\DCS\
- rename "Scripts" to something like "Scripts.backup" to keep it safe somewhere, just in case
- now follow the installation instructions for DCS-BIOS again.   It will think that DCS-BIOS has not been installed into that DCS installation and should write all the files again for you

Here are some other notes:

- reinstalling the OS has nothing to do with this, these are files that are considered part of your "user files" as far as windows is concerned so there is nothing windows can do, and even reinstalling it you would normally not throw away all your documents :)

- reinstalling DCS does nothing, as these files aren't installed with DCS but instead sit in your user account and survive reinstalling DCS

I hope some of these notes help.  I don't provide support for DCS-BIOS, but I can at least read logs so I figured I would try and translate.

**Comment by tao-jcqt** [comment]
Okay, thanks a lot for your help. That's really nice. So I'm gonna try to reinstall DCS Bios... But which version do I go for ? The last one (0.10) ?

**Comment by derammo** [comment]
you have to make sure that you do the renaming step to "hide" your scripts directory from the DCS-BIOS installation to make sure it gets recreated from scratch.   So don't just reinstall without doing that first.

I won't comment on your software choices, I am trying to respond to a potential bug report because there are almost no developers on this project.  So don't make me regret it :)

**Comment by tao-jcqt** [comment]
I just reinstalled DCS Bios version 0.10, everything went well : it recreated a new script folder. But it doesn't change anything : from the web interface if I use the TOGGLE function I have an answer in the simulator, but for the outputs I still have "No data yet"...

**Comment by derammo** [comment]
well is the error gone from dcs.log?   if so, then at least we corrected one of your problems.  Sorry I cannot help with figuring out how DCS-BIOS works, because I am not on that project.

**Comment by tao-jcqt** [comment]
Thanks again for helping me, no unfortunately the error is still there... I really don't understand what the problem is. Could someone who manages the project try to find a solution? I'm very frustrated not to be able to use this great software...
